"""empty message

Revision ID: dc3d6f029f5b
Revises: 2aecc4937deb
Create Date: 2022-10-21 11:54:44.088752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc3d6f029f5b'
down_revision = '2aecc4937deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_name', sa.String(length=64), nullable=True),
    sa.Column('caught', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pokemon_caught'), 'user_pokemon', ['caught'], unique=False)
    op.drop_index('ix_user__pokemon_caught', table_name='user__pokemon')
    op.drop_table('user__pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__pokemon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pokemon_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('caught', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user__pokemon_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user__pokemon_pkey')
    )
    op.create_index('ix_user__pokemon_caught', 'user__pokemon', ['caught'], unique=False)
    op.drop_index(op.f('ix_user_pokemon_caught'), table_name='user_pokemon')
    op.drop_table('user_pokemon')
    # ### end Alembic commands ###
