"""empty message

Revision ID: e2234b7608df
Revises: dc3d6f029f5b
Create Date: 2022-10-21 23:07:30.954493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2234b7608df'
down_revision = 'dc3d6f029f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_name', sa.String(length=64), nullable=True),
    sa.Column('caught', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pokemon_caught'), 'user_pokemon', ['caught'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_pokemon_caught'), table_name='user_pokemon')
    op.drop_table('user_pokemon')
    # ### end Alembic commands ###
